[package]
name = "day_03"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.2"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "day03_benchmarks"
harness = false

