[package]
name = "day_17"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.8.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "day17_benchmarks"
harness = false

