name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Change to the 2023 directory
      run: cd ./2023

    - name: Build
      run: cargo build --all --verbose

    - name: Run tests
      run: cargo test --all --verbose

    - name: Lint with Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

    # Optional: Run benchmarks (this can take a long time)
    # - name: Run Benchmarks
    #   run: cargo bench
